//===-- CPU74Subtarget.h - Define Subtarget for the CPU74 ----*- C++ -*--===//
//
//                     The LLVM Compiler Infrastructure
//
// This file is distributed under the University of Illinois Open Source
// License. See LICENSE.TXT for details.
//
//===----------------------------------------------------------------------===//
//
// This file declares the CPU74 specific subclass of TargetSubtargetInfo.
//
//===----------------------------------------------------------------------===//


#ifndef LLVM_LIB_TARGET_CPU74_CPU74SUBTARGET_H
#define LLVM_LIB_TARGET_CPU74_CPU74SUBTARGET_H

#include "CPU74FrameLowering.h"
#include "CPU74ISelLowering.h"
#include "CPU74InstrInfo.h"
#include "CPU74RegisterInfo.h"
#include "llvm/CodeGen/SelectionDAGTargetInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/IR/DataLayout.h"
#include <string>

#define GET_SUBTARGETINFO_HEADER
#include "CPU74GenSubtargetInfo.inc"


namespace llvm {
class StringRef;

class CPU74Subtarget : public CPU74GenSubtargetInfo
{

private:
  CPU74InstrInfo InstrInfo;
  CPU74FrameLowering FrameLowering;
  CPU74TargetLowering TLInfo;
  SelectionDAGTargetInfo TSInfo;

public:
  /// This constructor initializes the data members to match that
  /// of the specified triple.
  ///
  CPU74Subtarget(const Triple &TT, const std::string &CPU,
                  const std::string &FS, const CPU74TargetMachine &TM);

  /// ParseSubtargetFeatures - Parses features string setting specified
  /// subtarget options.  Definition of function is auto generated by tblgen.
  void ParseSubtargetFeatures(StringRef CPU, StringRef FS);
  const TargetFrameLowering *getFrameLowering() const override { return &FrameLowering; }
  const CPU74InstrInfo *getInstrInfo() const override { return &InstrInfo; }
  const TargetRegisterInfo *getRegisterInfo() const override { return &InstrInfo.getRegisterInfo(); }
  const CPU74TargetLowering *getTargetLowering() const override { return &TLInfo; }
  const SelectionDAGTargetInfo *getSelectionDAGInfo() const override { return &TSInfo; }
};
} // End llvm namespace


#endif  // LLVM_TARGET_CPU74_SUBTARGET_H


